### PR TITLE
Fix issue 4130

### LINKED ISSUE #4130: My code crashes the LDC compiler, while compiles just fine for DMD
The code in question: https://github.com/ZILtoid1991/newxml

Under LDC2, it crashes with an access violation/segfault. So far, I have tried Windows/x86-64 and Linux/AArch64, all the same issue. With this code, I used to have an issue of segfaulting DMD too, but that was a constructor call issue that I had to solve with the `DOMImplementation.Element.createMap` function, since calling the ctor of `DOMImplementation.Element.Map` from `DOMImplementation.Document` caused issues.

### PR DESCRIPTION
**Pull request by thewilsonator**
This fixes the issue, I'm not sure if the correct thing to do is to make DMD not emit bogus ASTs to begin with.

fixes #4130

### CODE REVIEW

File: tests/codegen/gh4130.d [hunk 1]
```diff
@@ -0,0 +1,21 @@
+// RUN: %ldc -c %s
+
+class A
+{
+    class B { B b; }
+    class C
+    {
+        B b;
```
Comment (JohanEngelen) [inline tests/codegen/gh4130.d:8]: I think it is nicer to not name every variable `b`. It makes it harder to figure out what is going on.

File: gen/nested.cpp [hunk 2]
```diff
@@ -307,7 +307,8 @@ LLValue *DtoNestedContext(const Loc &loc, Dsymbol *sym) {
     IF_LOG Logger::println("Current function is %s", ctxfd->toChars());
     if (fromParent) {
       ctxfd = getParentFunc(ctxfd);
-      assert(ctxfd && "Context from outer function, but no outer function?");
+      if (!ctxfd)
+        ctxfd = irFunc.decl;
```
Comment (JohanEngelen) [inline gen/nested.cpp:311]: add log output about this strange case?

Comment (JohanEngelen) [reply gen/nested.cpp:311]: does this actually produce correct code now?

Comment (thewilsonator) [reply gen/nested.cpp:311]: It doesn't crash, which is what it did before. As for the correctness of the code,I'm not really sure, but I don't know what its supposed to do other than iterate through the linked list of classes. @ZILtoid1991 could you provide a reduced test case of this code in action?

Comment (ZILtoid1991) [reply gen/nested.cpp:311]:
```d
class DOMImplementation {
class Attr  {  Attr  _nextAttr; }
class Map  {
    Attr firstAttr;
    auto opSlice()
    {
         struct Range
         {
             Attr currentAttr;

             auto front() { return currentAttr; }
             void popFront() { currentAttr = currentAttr._nextAttr; }
             bool empty() { return currentAttr is null; }
        }
       return Range(firstAttr);
   }
}
}
```

Comment (kinke) [reply gen/nested.cpp:311]: Thx, somewhat further reduced:
```D
class Outer {
    class Inner {
        auto opSlice() {
            struct Range {
                void foo() {}
            }
            return Range();
        }
    }
}
```

**2** outer aggregates are apparently required, and both need to be classes (works with any one of them being a struct).

Comment (JohanEngelen) [reply gen/nested.cpp:311]: > It doesn't crash, which is what it did before. As for the correctness of the code,I'm not really sure, but I don't know what its supposed to do other than iterate through the linked list of classes. 

If unsure about the correct behavior, then better to exit gracefully instead of silently continuing.
