### PR TITLE
Sync command-line options and descriptions with DMD

### LINKED ISSUE #1923: Description of -w/-wi flags is misleading
Using LDC 1.1.0 Beta6

It looks like when compiling a D file that has warnings, supplying the -w flag will make the compilation fail - AFAIR this hasn't happened with previous releases, and the documentation suggests that this will only show warnings and not stop the compilation.

So, is the documentation or the LDC behavior wrong?

### PR DESCRIPTION
**Pull request by kinke**
Resolves #1923.

### CODE REVIEW

File: driver/ldmd.cpp [hunk 1]
```diff
@@ -175,53 +176,58 @@ Usage:\n\
...
+  -gc            add symbolic debug info, optimize for non D debuggers\n\
+  -gs            always emit stack frame\n"
+#if 0
+"  -gx            add stack stomp code\n"
+#endif
+"  -H             generate 'header' file\n\
   -Hddirectory   write 'header' file to directory\n\
   -Hffilename    write 'header' file to filename\n\
-  --help         print help\n\
+  --help         print help and exit\n\
```
Comment (wilzbach) [inline driver/ldmd.cpp]: DMD supports `-h` as well since 2.072

Comment (kinke) [inline driver/ldmd.cpp]: I don't see it in the DMD 2.072.2 usage output and neither in [current source](https://github.com/dlang/dmd/blob/master/src/mars.d#L138)...

Comment (wilzbach) [inline driver/ldmd.cpp]: > I don't see it in the DMD 2.072.2 usage output and neither in current source. But there have been some more tweaks in 2.072.

Yeah it's hidden, because Walter and Andrei were a bit against it, but they couldn't say no against printing the help page in case someone typed `-h` as it's common behavior in the Unix world. So I am not sure whether you want to support/display it or not.

The current `dmd` frontend does accept `-h`:

https://github.com/dlang/dmd/blob/master/src/mars.d#L913

And the PRs with the discussion:

https://github.com/dlang/dmd/pull/5844/files
https://github.com/dlang/dmd/pull/5806

Comment (kinke) [inline driver/ldmd.cpp]: Ah thanks, but the 2.072 changes will be reflected in a later PR, this one is still aimed for LDC 1.1.
