### PR TITLE
Fix identity comparisons of complex numbers

### LINKED ISSUE #2918: Broken IdentityExp comparison for complex floats
See https://bugzilla.gdcproject.org/show_bug.cgi?id=309

Part of the test program fails with LDC too.

```d
void main()
{
    creal f1 = +0.0 + 0.0i;
    creal f2 = +0.0 - 0.0i;
    creal f3 = -0.0 + 0.0i;
    creal f4 = +0.0 + 0.0i;
    assert(f1 !is f2);
    assert(f1 !is f3);
    assert(f2 !is f3);
    assert(f1 is f4);
    assert(!(f1 is f2)); // fails
    assert(!(f1 is f3)); // fails
    assert(!(f2 is f3));
    assert(!(f1 !is f4));
}
```

### PR DESCRIPTION
**Pull request by kinke**
Obviously *both* real and imaginary parts need to be identical.
Fixes #2918.

### CODE REVIEW

File: gen/complex.cpp [hunk 1]
```diff
@@ -421,10 +421,8 @@ LLValue *DtoComplexEquals(Loc &loc, TOK op, DValue *lhs, DValue *rhs) {
   LLValue *b1 = DtoBinFloatsEquals(loc, lhs_re, rhs_re, op);
   LLValue *b2 = DtoBinFloatsEquals(loc, lhs_im, rhs_im, op);
 
-  if (op == TOKequal) {
-    return gIR->ir->CreateAnd(b1, b2);
-  }
-  return gIR->ir->CreateOr(b1, b2);
+  return op == TOKequal || op == TOKidentity ? gIR->ir->CreateAnd(b1, b2)
```
Comment (JohanEngelen) [inline gen/complex.cpp]: Nit: parens around the part before `?` help readability.

Otherwise lgtm.
