### PR TITLE
Cache struct literal constants per compilation unit, not globally

### LINKED ISSUE #2990: Problem with build protobuf-d
```dub build :protoc-gen-d
Building package protobuf:protoc-gen-d in /home/deviator/tests/dtest/usbdev/protobuf-d/protoc_gen_d/
Performing "debug" build using /opt/ldc2/bin/ldc2 for x86_64.
protobuf ~master: building configuration "protobuf"...
Invalid bitcast
%std.datetime.timezone.TimeZone* bitcast (/opt/ldc2/bin/ldc2(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamE+0x1a)[0x2a600da]
/opt/ldc2/bin/ldc2(_ZN4llvm3sys17RunSignalHandlersEv+0x35)[0x2a5e7d5]
/opt/ldc2/bin/ldc2[0x2a5e8ec]
/lib64/libpthread.so.0(+0x11fb0)[0x7f7db1c70fb0]
/opt/ldc2/bin/ldc2(_ZTV8DImValue+0x10)[0x3c8e748]
/opt/ldc2/bin/ldc2 failed with exit code -11.
```

protobuf-d: `0.4.1` from github releases
OS: `Fedora 28 4.19.13-200`
ldc: `1.13.0` from github releases (on `1.12.0` too)
dub: `1.12.1`

### PR DESCRIPTION
**Pull request by kinke**
Fixes #2990.

I don't have a reduced testcase.

### CODE REVIEW

File: gen/irstate.cpp [hunk 1]
```diff
@@ -180,6 +180,17 @@ void IRState::replaceGlobals() {
 
 ////////////////////////////////////////////////////////////////////////////////
 
+LLConstant *IRState::getStructLiteralConstant(StructLiteralExp *sle) const {
+  return static_cast<LLConstant *>(structLiteralConstants.lookup(sle));
```
Comment (JohanEngelen) [inline gen/irstate.cpp]: nit: use `llvm::Constant` instead of `LLConstant`.

Comment (kinke) [reply gen/irstate.cpp]: C'mon, I prefer those.

File: gen/irstate.h [hunk 2]
```diff
@@ -111,6 +113,12 @@ struct IRState {
   std::vector<std::pair<llvm::GlobalVariable *, llvm::Constant *>>
       globalsToReplace;
 
+  // Cache of (possibly bitcast) global variables for taking the address of
+  // struct literal constants. Used to resolve self-references.
+  // [The real key type is `StructLiteralExp *`; a fwd class declaration isn't
+  // enough to use it directly.]
+  llvm::DenseMap<void *, llvm::Constant *> structLiteralConstants;
```
Comment (JohanEngelen) [inline gen/irstate.h]: because there is no testcase for it, i think it'd be good to add to the comment here that the caching is intentionally per TU (and not per StructLiteralExp).

Comment (kinke) [reply gen/irstate.h]: I added a sentence.
