### PR TITLE
Traverse full chain of nested aggregates when resolving a nested variable

### LINKED ISSUE #3556: Calling a method of the outermost class from a class defined in a multiple stratum in a method causes a Segfault (LDC2 1.23.0)
When I compile and run this code, I get a segfault. There was no problem with dmd 2.093.1.

```D
import std.stdio;

class C {
    void func() {
        writeln("hello world!");
    }
    void run1() {
        class C2 {
            class C3 {
                void run3() {
                    func();
                }
            }
            void run2() {
                auto c3 = new C3;
                c3.run3();
            }
        }
        auto c2 = new C2;
        c2.run2();
    }
}

void main() {
    auto c = new C;
    c.run1();
}
```

Windows 10 Pro (64-bit):

    $ ldc2-1.23.0-windows-multilib\bin\ldc2 -run test.d
    Error: C:\Users\***\AppData\Local\Temp\test-417097a-fa96f5.exe failed with status: -1073741819
    Error: program received signal 1073741819

Linux Mint 19.3 (64-bit):

    $ ldc2-1.23.0-linux-x86_64/bin/ldc2 -run test.d
    Error: /tmp/test-896560f-8a2e3b failed with status: -2
           message: Segmentation fault (core dumped)
    Error: program received signal 2 (Interrupt)

### PR DESCRIPTION
**Pull request by kinke**
Fixes #3556.

### CODE REVIEW

**Comment by kinke** [comment]
Not too sure about this fix, I'm not really familiar with this `vthis` business.

File: gen/nested.cpp [hunk 1]
```diff
@@ -455,17 +455,13 @@ void DtoCreateNestedContext(FuncGenState &funcGen) {
...
+        assert(ad->vthis);
+        LLValue *thisptr =
+            ad->isClassDeclaration() ? DtoLoad(irFunc.thisArg) : irFunc.thisArg;
         IF_LOG Logger::println("Indexing to 'this'");
-        if (cd->isStructDeclaration()) {
-          src = DtoExtractValue(thisval, getVthisIdx(cd), ".vthis");
-        } else {
-          src = DtoLoad(DtoGEP(thisval, 0, getVthisIdx(cd), ".vthis"));
-        }
+        src = DtoLoad(DtoGEP(thisptr, 0, getVthisIdx(ad), ".vthis"));
```
Comment (kinke) [inline gen/nested.cpp:464]: This is unrelated but seemed really ugly - loading the whole struct, just to extract the vthis part, instead of loading the vthis part only.
