### PR TITLE
Fix casting (static and dynamic) arrays to vectors

### LINKED ISSUE #3418: wrong code for `cast` static_array->vector
```d
auto bar3(ref ubyte[64] a, ref ubyte[64] b)
{
    a = (cast(__vector(ubyte[64]))b).array;
}
```
for -mcpu=haswell
```asm
pure nothrow @nogc @safe void example.bar3(ref ubyte[64], ref ubyte[64]):
        vpbroadcastb    ymm0, byte ptr [rdi]
        vmovdqu ymmword ptr [rsi + 32], ymm0
        vmovdqu ymmword ptr [rsi], ymm0
        vzeroupper
        ret
```
expected
```asm
pure nothrow @nogc @safe void example.bar4(ref __vector(ubyte[64]), ref ubyte[64]):
        vmovups ymm0, ymmword ptr [rdi]
        vmovups ymm1, ymmword ptr [rdi + 32]
        vmovups ymmword ptr [rsi + 32], ymm1
        vmovups ymmword ptr [rsi], ymm0
        vzeroupper
        ret

```
expected is generated from:
```d
auto bar4(ref __vector(ubyte[64]) a, ref ubyte[64] b)
{
    a.array[] = b;
}
```

### PR DESCRIPTION
**Pull request by kinke**
Fixes #3418.

### CODE REVIEW

File: tests/codegen/vector_init.d [hunk 1]
```diff
@@ -37,3 +37,25 @@ void foo()
...
+    alias float4 = __vector(float[4]);
+    alias int4 = __vector(int[4]);
+
+    // CHECK: %[[f:[0-9]+]] = bitcast <4 x float>* %f to i8*
+    // CHECK: call void @llvm.memcpy{{.*}}(i8*{{[^,]*}} %[[f]]
+    auto f = cast(float4) floats;
+
+    // CHECK: %[[i:[0-9]+]] = bitcast <4 x i32>* %i to i8*
+    // CHECK: call void @llvm.memcpy{{.*}}(i8*{{[^,]*}} %[[i]]
+    auto i = cast(int4) ints;
```
Comment (kinke) [inline tests/codegen/vector_init.d:54]: If we want a bounds check at some point, it should probably be added in the frontend.

File: tests/codegen/vector_init.d [hunk 2]
```diff
@@ -37,3 +37,25 @@ void foo()
...
+
+    // CHECK: fptosi
+    // CHECK: fptosi
+    // CHECK: fptosi
+    // CHECK: fptosi
+    auto converted = cast(int4) floats;
```
Comment (kinke) [inline tests/codegen/vector_init.d:60]: Casting a vector is a reinterpret-cast (currently at least), casting a src array converts... ;)
