### PR TITLE
Refactor DVarValue handling; fix dumping ToElemVisitor result to stack slot

### LINKED ISSUE #1294: Instruction does not dominate all uses! (compiling botan)
When running `dub test` in current [Botan](https://github.com/etcimon/botan/commit/0c101c09bd220bc03f0bb97c7ad77033cb7f4eda), I get the following errors:

```
Instruction does not dominate all uses!
  %58 = load %botan.math.bigint.bigint.BigInt*, %botan.math.bigint.bigint.BigInt** %condtmp, !dbg !923
  %69 = bitcast %botan.math.bigint.bigint.BigInt* %58 to i8*, !dbg !923
Instruction does not dominate all uses!
  %106 = load %botan.math.bigint.bigint.BigInt*, %botan.math.bigint.bigint.BigInt** %condtmp20, !dbg !928
  %116 = bitcast %botan.math.bigint.bigint.BigInt* %106 to i8*, !dbg !928
Instruction does not dominate all uses!
  %151 = load %botan.math.bigint.bigint.BigInt*, %botan.math.bigint.bigint.BigInt** %condtmp43, !dbg !933
  %161 = bitcast %botan.math.bigint.bigint.BigInt* %151 to i8*, !dbg !933
```

This might be related to https://github.com/ldc-developers/ldc/issues/1042

### PR DESCRIPTION
**Pull request by klickverbot**
See the commit descriptions for details (most changes are just refactorings).

Fixes #1294 (both by avoiding the issue, as well as fixing potentially undiscovered similar issues by tackling the root cause).

### CODE REVIEW

**Comment by kinke** [comment]
Maybe just a GitHub issue. I've had a few in the last couple of weeks, something I've never had before.

**Comment by redstar** [comment]
@klickverbot IMHO I forgot to push the runtime/druntime commit.

File: gen/toir.cpp [hunk 1]
```diff
@@ -283,11 +288,12 @@ class ToElemVisitor : public Visitor {
   DValue *getResult() {
     if (destructTemporaries &&
         p->func()->scopes->currentCleanupScope() != initialCleanupScope) {
-      // If the results is an (LLVM) r-value, temporarily store it in an
-      // alloca slot to avoid running into instruction dominance issues
-      // if we share the cleanups with another exit path (e.g. unwinding).
+      // We might share the CFG edges through the below cleanup blocks with
+      // other paths (e.g. exception unwinding) where the result value has not
+      // been constructed. The runtime branches will be chosen such that the end
+      // bb (which can access the value) is never executed, but to make sure .
```
Comment (kinke) [inline gen/toir.cpp]: Something missing at the end of the comment?

Lgtm, feel free to merge.
