### PR TITLE
Fix #4938 - Be stricter wrt. supported AddrExp in toConstElem()

### LINKED ISSUE #4938: module-level non-constant expression crashes instead of reporting error
```
import std.utf : toUTF16z;

auto x = "whoops".toUTF16z;

void main()
{
}
```

DMD (v2.111.0): 

`app.d(3,18): Error: non-constant expression ``&['w', 'h', 'o', 'o', 'p', 's', '\0'][0]`

LDC2 (1.40.1) and (1.41.0-beta1):
```
Exception Code: 0xC0000005
0x00007FF656764D7C, R:\tools\dlang\ldc2-1.41.0-beta1-windows-x64\bin\ldc2.exe(0x00007FF653210000) + 0x3554D7C byte(s)
0x00007FF6566D4DEF, R:\tools\dlang\ldc2-1.41.0-beta1-windows-x64\bin\ldc2.exe(0x00007FF653210000) + 0x34C4DEF byte(s)
0x00007FF656738F42, R:\tools\dlang\ldc2-1.41.0-beta1-windows-x64\bin\ldc2.exe(0x00007FF653210000) + 0x3528F42 byte(s)
0x00007FF656763925, R:\tools\dlang\ldc2-1.41.0-beta1-windows-x64\bin\ldc2.exe(0x00007FF653210000) + 0x3553925 byte(s)
0x00007FF65329E6D8, R:\tools\dlang\ldc2-1.41.0-beta1-windows-x64\bin\ldc2.exe(0x00007FF653210000) + 0x8E6D8 byte(s)
0x00007FF656A8E0CF, R:\tools\dlang\ldc2-1.41.0-beta1-windows-x64\bin\ldc2.exe(0x00007FF653210000) + 0x387E0CF byte(s)
0x00007FF656702D3B, R:\tools\dlang\ldc2-1.41.0-beta1-windows-x64\bin\ldc2.exe(0x00007FF653210000) + 0x34F2D3B byte(s)
0x00007FF65683A406, R:\tools\dlang\ldc2-1.41.0-beta1-windows-x64\bin\ldc2.exe(0x00007FF653210000) + 0x362A406 byte(s)
0x00007FF65683A04E, R:\tools\dlang\ldc2-1.41.0-beta1-windows-x64\bin\ldc2.exe(0x00007FF653210000) + 0x362A04E byte(s)
0x00007FF65683A366, R:\tools\dlang\ldc2-1.41.0-beta1-windows-x64\bin\ldc2.exe(0x00007FF653210000) + 0x362A366 byte(s)
0x00007FF6566FC341, R:\tools\dlang\ldc2-1.41.0-beta1-windows-x64\bin\ldc2.exe(0x00007FF653210000) + 0x34EC341 byte(s)
0x00007FF656AB5A80, R:\tools\dlang\ldc2-1.41.0-beta1-windows-x64\bin\ldc2.exe(0x00007FF653210000) + 0x38A5A80 byte(s)
0x00007FFB2871E8D7, C:\WINDOWS\System32\KERNEL32.DLL(0x00007FFB286F0000) + 0x2E8D7 byte(s), BaseThreadInitThunk() + 0x17 byte(s)
0x00007FFB2A29C5DC, C:\WINDOWS\SYSTEM32\ntdll.dll(0x00007FFB2A200000) + 0x9C5DC byte(s), RtlUserThreadStart() + 0x2C byte(s)
Error ldc2 failed with exit code -1073741819.
```

### PR DESCRIPTION
**Pull request by kinke**
DMD seems to support AddrExp of struct literals only...

### CODE REVIEW

File: gen/toconstelem.cpp [hunk 1]
```diff
@@ -401,7 +401,7 @@ class ToConstElemVisitor : public Visitor {
       return;
     }
 
-    // address of indexExp
+    /* address of indexExp
```
Comment (kinke) [inline gen/toconstelem.cpp:404]: [for now just checking whether we hit this case anywhere in the testsuite]
